apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secrets
type: Opaque
data:
  SPRING_DATA_MONGODB_URI: bW9uZ29kYitzcnY6Ly9jdHNlOmN0c2UxMjNAY2x1c3RlcjAuMWpzb2kubW9uZ29kYi5uZXQvaW52ZW50b3J5X2N0c2U/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=