apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 2
  selector: { matchLabels: { app: inventory-service }}
  template:
    metadata: { labels: { app: inventory-service }}
    spec:
      containers:
        - name: inventory-service
          image: 630288222109.dkr.ecr.us-east-1.amazonaws.com/inventory-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secrets
                  key: SPRING_DATA_MONGODB_URI
          imagePullPolicy: Always