apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
type: Opaque
data:
  SPRING_DATA_MONGODB_URI: bW9uZ29kYitzcnY6Ly9jdHNlOmN0c2UxMjNAY2x1c3RlcjAuMWpzb2kubW9uZ29kYi5uZXQvb3JkZXJfY3RzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==