apiVersion: v1
kind: Service # Service YAML
metadata:
  name: product-service
spec:
  selector: { app: product-service } # Selects pods with label app=product-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP  # Default service type; exposes the service on an internal IP